import * as stylex from "@stylexjs/stylex";
import { colors } from "./tokens.stylex";

export const s = stylex.create({
  app: { minHeight: "100vh", backgroundColor: colors.bg, color: colors.text },
  header: { position: "sticky", top: 0, zIndex: 20, display: "grid", gridTemplateColumns: "auto minmax(200px, 720px) auto", gap: 16, alignItems: "center", padding: "12px 20px", backgroundColor: "rgba(9,9,11,.94)", borderBottomWidth: 1, borderBottomStyle: "solid", borderBottomColor: colors.border, backdropFilter: "blur(16px)" },
  brand: { textDecoration: "none", fontWeight: 900, letterSpacing: "-0.04em", fontSize: 22, whiteSpace: "nowrap" },
  brandAccent: { color: colors.accent },
  searchWrap: { display: "flex", minWidth: 0 },
  searchInput: { width: "100%", backgroundColor: colors.panelRaised, color: colors.text, borderWidth: 1, borderStyle: "solid", borderColor: colors.border, borderRadius: 8, padding: "10px 12px", outline: "none" },
  nav: { display: "flex", gap: 12, alignItems: "center", fontSize: 13, color: colors.muted },
  navLink: { color: "inherit", textDecoration: "none", ':hover': { color: colors.text } },
  page: { width: "min(1600px, 100%)", margin: "0 auto", padding: "18px 20px 40px" },
  columns: { display: "grid", gridTemplateColumns: "210px minmax(0, 1fr) 250px", gap: 20, alignItems: "start", '@media (max-width: 1100px)': { gridTemplateColumns: "180px minmax(0,1fr)" }, '@media (max-width: 760px)': { gridTemplateColumns: "1fr" } },
  leftRail: { position: "sticky", top: 78, '@media (max-width: 760px)': { position: "static" } },
  rightRail: { position: "sticky", top: 78, '@media (max-width: 1100px)': { display: "none" } },
  sectionTitle: { margin: "0 0 10px", fontSize: 12, textTransform: "uppercase", letterSpacing: ".12em", color: colors.muted },
  railBox: { backgroundColor: colors.panel, borderWidth: 1, borderStyle: "solid", borderColor: colors.border, borderRadius: 10, padding: 12, marginBottom: 14 },
  railLink: { display: "block", padding: "7px 8px", color: colors.text, textDecoration: "none", fontSize: 14, borderRadius: 6, ':hover': { backgroundColor: colors.panelRaised } },
  contentHeader: { display: "flex", alignItems: "end", justifyContent: "space-between", gap: 16, marginBottom: 14 },
  heading: { margin: 0, fontSize: 22, letterSpacing: "-0.03em" },
  subheading: { margin: "5px 0 0", color: colors.muted, fontSize: 13 },
  chips: { display: "flex", gap: 8, overflowX: "auto", paddingBottom: 12, scrollbarWidth: "none" },
  chip: { borderWidth: 1, borderStyle: "solid", borderColor: colors.border, backgroundColor: colors.panel, color: colors.text, borderRadius: 999, padding: "7px 11px", whiteSpace: "nowrap", cursor: "pointer", textDecoration: "none", ':hover': { borderColor: colors.accent } },
  directory: { marginBottom: 18, backgroundColor: colors.panel, borderWidth: 1, borderStyle: "solid", borderColor: colors.border, borderRadius: 10, overflow: "hidden" },
  directoryHead: { display: "flex", justifyContent: "space-between", gap: 12, alignItems: "center", padding: "11px 13px", borderBottomWidth: 1, borderBottomStyle: "solid", borderBottomColor: colors.border },
  directoryGrid: { display: "grid", gridTemplateColumns: "repeat(2,minmax(0,1fr))", '@media (max-width: 650px)': { gridTemplateColumns: "1fr" } },
  directoryItem: { display: "grid", gridTemplateColumns: "1fr auto", gap: 12, padding: "12px 13px", textDecoration: "none", borderBottomWidth: 1, borderBottomStyle: "solid", borderBottomColor: colors.border, ':hover': { backgroundColor: colors.panelRaised } },
  directoryTitle: { fontWeight: 750, fontSize: 14, marginBottom: 3 },
  directoryDescription: { color: colors.muted, fontSize: 12, lineHeight: 1.4 },
  directoryBadge: { alignSelf: "start", padding: "3px 6px", borderRadius: 999, backgroundColor: colors.panelRaised, color: colors.muted, fontSize: 10, textTransform: "uppercase", letterSpacing: ".06em" },
  grid: { display: "grid", gridTemplateColumns: "repeat(4, minmax(0, 1fr))", gap: "18px 12px", '@media (max-width: 1250px)': { gridTemplateColumns: "repeat(3,minmax(0,1fr))" }, '@media (max-width: 850px)': { gridTemplateColumns: "repeat(2,minmax(0,1fr))" }, '@media (max-width: 480px)': { gridTemplateColumns: "1fr" } },
  card: { color: colors.text, textDecoration: "none", minWidth: 0 },
  thumbWrap: { position: "relative", aspectRatio: "16 / 9", overflow: "hidden", borderRadius: 8, backgroundColor: colors.panelRaised, borderWidth: 1, borderStyle: "solid", borderColor: colors.border },
  thumb: { width: "100%", height: "100%", objectFit: "cover", transition: "transform .18s ease", ':hover': { transform: "scale(1.025)" } },
  duration: { position: "absolute", right: 6, bottom: 6, padding: "3px 6px", borderRadius: 4, backgroundColor: "rgba(0,0,0,.78)", fontSize: 11, fontWeight: 700 },
  provider: { position: "absolute", left: 6, top: 6, padding: "3px 6px", borderRadius: 4, backgroundColor: "rgba(0,0,0,.78)", fontSize: 10, textTransform: "uppercase", letterSpacing: ".08em" },
  cardTitle: { margin: "7px 0 3px", fontSize: 14, fontWeight: 650, lineHeight: 1.3, overflow: "hidden", display: "-webkit-box", WebkitLineClamp: 2, WebkitBoxOrient: "vertical" },
  meta: { color: colors.muted, fontSize: 12 },
  panel: { backgroundColor: colors.panel, borderWidth: 1, borderStyle: "solid", borderColor: colors.border, borderRadius: 10, padding: 16 },
  player: { width: "100%", aspectRatio: "16 / 9", border: 0, borderRadius: 10, backgroundColor: "#000" },
  playerTitle: { margin: "14px 0 6px", fontSize: 22 },
  tags: { display: "flex", flexWrap: "wrap", gap: 7, marginTop: 12 },
  tag: { backgroundColor: colors.panelRaised, borderRadius: 999, padding: "5px 9px", fontSize: 12, color: colors.muted, textDecoration: "none" },
  footer: { marginTop: 28, padding: "24px 20px 40px", borderTopWidth: 1, borderTopStyle: "solid", borderTopColor: colors.border, color: colors.muted, fontSize: 12 },
  footerInner: { width: "min(1600px,100%)", margin: "0 auto", display: "flex", flexWrap: "wrap", gap: 12, justifyContent: "space-between" },
  footerLinks: { display: "flex", flexWrap: "wrap", gap: 12 },
  gate: { position: "fixed", inset: 0, zIndex: 100, display: "grid", placeItems: "center", backgroundColor: "rgba(0,0,0,.88)", padding: 20 },
  gateCard: { width: "min(460px,100%)", padding: 24, borderRadius: 14, backgroundColor: colors.panel, borderWidth: 1, borderStyle: "solid", borderColor: colors.border, boxShadow: "0 30px 80px rgba(0,0,0,.5)" },
  gateTitle: { margin: "0 0 8px", fontSize: 28 },
  gateText: { margin: "0 0 18px", color: colors.muted, lineHeight: 1.55 },
  primaryButton: { border: 0, borderRadius: 8, padding: "10px 14px", backgroundColor: colors.accent, color: "#fff", fontWeight: 800, cursor: "pointer" },
  secondaryButton: { borderWidth: 1, borderStyle: "solid", borderColor: colors.border, borderRadius: 8, padding: "10px 14px", backgroundColor: colors.panelRaised, color: colors.text, cursor: "pointer", textDecoration: "none" },
  buttonRow: { display: "flex", gap: 10, flexWrap: "wrap" },
  status: { display: "flex", alignItems: "center", justifyContent: "space-between", gap: 10, padding: "7px 0", fontSize: 13 },
  dotOn: { width: 7, height: 7, borderRadius: 999, backgroundColor: colors.success },
  dotOff: { width: 7, height: 7, borderRadius: 999, backgroundColor: colors.muted },
  form: { display: "grid", gap: 12 },
  label: { display: "grid", gap: 6, fontSize: 13, color: colors.muted },
  input: { width: "100%", backgroundColor: colors.panelRaised, color: colors.text, borderWidth: 1, borderStyle: "solid", borderColor: colors.border, borderRadius: 8, padding: "10px 11px", outline: "none" },
  textarea: { width: "100%", minHeight: 150, resize: "vertical", backgroundColor: colors.panelRaised, color: colors.text, borderWidth: 1, borderStyle: "solid", borderColor: colors.border, borderRadius: 8, padding: "10px 11px", outline: "none" },
  prose: { maxWidth: 820, lineHeight: 1.65, color: "#d5d5da" },
});
